#!/usr/bin/env node
/**
 * Copy Source Sans 3 woff2 subsets into webui/fonts/ and emit fonts.css (FR-039).
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const webuiDir = path.resolve(root, "../src/main/resources/webui");
const fontsOutDir = path.join(webuiDir, "fonts");
const fontPkgDir = path.join(root, "node_modules/@fontsource/source-sans-3");
const fontFilesDir = path.join(fontPkgDir, "files");

const WEIGHTS = [400, 600, 700];
const SUBSETS = ["latin", "latin-ext", "cyrillic", "cyrillic-ext"];

function readSubsetCss(weight, subset) {
  const file = path.join(fontPkgDir, `${subset}-${weight}.css`);
  if (!fs.existsSync(file)) {
    throw new Error("Missing fontsource CSS: " + file);
  }
  return fs.readFileSync(file, "utf8");
}

function woff2Name(subset, weight) {
  return `source-sans-3-${subset}-${weight}-normal.woff2`;
}

fs.mkdirSync(fontsOutDir, { recursive: true });

const cssBlocks = [];
for (const weight of WEIGHTS) {
  for (const subset of SUBSETS) {
    const name = woff2Name(subset, weight);
    const src = path.join(fontFilesDir, name);
    if (!fs.existsSync(src)) {
      throw new Error("Missing font file: " + src);
    }
    const dest = path.join(fontsOutDir, name);
    fs.copyFileSync(src, dest);
    const block = readSubsetCss(weight, subset).replace(
      /src:\s*url\(\.\/files\/[^)]+\)[^;]+;/,
      "src: url(/fonts/" + name + ") format('woff2');"
    );
    cssBlocks.push(block.trim());
    console.log("OK font " + name);
  }
}

const fontsCss =
  "/* Source Sans 3 — self-hosted (FR-039). Generated by npm run build:fonts */\n\n" +
  cssBlocks.join("\n\n") +
  "\n";

fs.writeFileSync(path.join(webuiDir, "fonts.css"), fontsCss, "utf8");
console.log("OK fonts.css -> " + path.join(webuiDir, "fonts.css"));
