package com.avandocmsg.messenger.api.chats;

import com.avandocmsg.messenger.api.config.AppConfig;
import com.avandocmsg.messenger.api.repository.MessageRepository;
import com.avandocmsg.messenger.core.adapter.persistence.JdbcChatPersistenceAdapter;
import com.avandocmsg.messenger.core.adapter.persistence.JdbcChatReadStateAdapter;
import com.avandocmsg.messenger.core.adapter.persistence.JdbcMessageReadReceiptAdapter;
import com.avandocmsg.messenger.core.adapter.persistence.JdbcMessageRepositoryAdapter;
import com.avandocmsg.messenger.core.adapter.persistence.JdbcUserLookupAdapter;
import com.avandocmsg.messenger.core.port.AuditPort;
import com.avandocmsg.messenger.core.port.MessageRepositoryPort;
import com.avandocmsg.messenger.core.port.NatsOutboundPort;
import com.avandocmsg.messenger.core.adapter.cache.NoOpReadCacheAdapter;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Statement;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ReadReceiptServiceH2Test {

    private HikariDataSource ds;
    private ReadReceiptService service;
    private UUID chatId;
    private UUID senderId;
    private UUID readerId;
    private UUID messageId;

    @BeforeEach
    void init() throws Exception {
        chatId = UUID.randomUUID();
        senderId = UUID.randomUUID();
        readerId = UUID.randomUUID();
        messageId = UUID.randomUUID();
        var cfg = new HikariConfig();
        cfg.setJdbcUrl("jdbc:h2:mem:rrsvc_" + UUID.randomUUID().toString().replace("-", "")
            + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
        cfg.setMaximumPoolSize(4);
        ds = new HikariDataSource(cfg);
        try (var c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE users (id UUID PRIMARY KEY, display_name VARCHAR(128), privacy_disable_read_receipts BOOLEAN NOT NULL DEFAULT false)");
            st.execute("""
                CREATE TABLE chats (
                  id UUID PRIMARY KEY,
                  title VARCHAR(256) NOT NULL DEFAULT '',
                  type VARCHAR(16) NOT NULL DEFAULT 'group',
                  owner_id UUID REFERENCES users(id)
                )
                """);
            st.execute("""
                CREATE TABLE chat_members (
                  chat_id UUID NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
                  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                  role VARCHAR(16) NOT NULL DEFAULT 'member',
                  banned BOOLEAN NOT NULL DEFAULT false,
                  personal_filter_active BOOLEAN NOT NULL DEFAULT false,
                  PRIMARY KEY (chat_id, user_id)
                )
                """);
            st.execute("""
                CREATE TABLE messages (
                  id UUID PRIMARY KEY,
                  chat_id UUID NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
                  sender_id UUID NOT NULL REFERENCES users(id),
                  client_msg_id VARCHAR(64),
                  type VARCHAR(16) NOT NULL DEFAULT 'text',
                  content TEXT,
                  reply_to_msg_id UUID,
                  thread_id UUID,
                  deleted BOOLEAN NOT NULL DEFAULT false,
                  visibility_ttl_seconds INT,
                  attachment_file_id UUID,
                  voice_duration_ms INT,
                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  edited_at TIMESTAMP
                )
                """);
            st.execute("""
                CREATE TABLE chat_read_state (
                  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                  chat_id UUID NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
                  last_read_message_id UUID REFERENCES messages(id) ON DELETE SET NULL,
                  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  PRIMARY KEY (user_id, chat_id)
                )
                """);
            st.execute("""
                CREATE TABLE message_read_receipts (
                  message_id UUID NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
                  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                  read_at TIMESTAMP NOT NULL,
                  PRIMARY KEY (message_id, user_id)
                )
                """);
            st.execute("""
                CREATE TABLE audit_events (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  actor_user_id UUID,
                  action VARCHAR(64) NOT NULL,
                  resource_type VARCHAR(64) NOT NULL,
                  resource_id VARCHAR(128),
                  details_json TEXT
                )
                """);
        }
        insertUser(senderId);
        insertUser(readerId);
        try (var c = ds.getConnection();
             var ps = c.prepareStatement("INSERT INTO chats (id, title, type, owner_id) VALUES (?, 't', 'group', ?)")) {
            ps.setObject(1, chatId);
            ps.setObject(2, senderId);
            ps.executeUpdate();
        }
        try (var c = ds.getConnection();
             var ps = c.prepareStatement("INSERT INTO chat_members (chat_id, user_id, role) VALUES (?, ?, 'member')")) {
            ps.setObject(1, chatId);
            ps.setObject(2, senderId);
            ps.addBatch();
            ps.setObject(1, chatId);
            ps.setObject(2, readerId);
            ps.addBatch();
            ps.executeBatch();
        }
        try (var c = ds.getConnection();
             var ps = c.prepareStatement("""
                 INSERT INTO messages (id, chat_id, sender_id, type, content, deleted, created_at)
                 VALUES (?, ?, ?, 'text', 'hello', false, CURRENT_TIMESTAMP)
                 """)) {
            ps.setObject(1, messageId);
            ps.setObject(2, chatId);
            ps.setObject(3, senderId);
            ps.executeUpdate();
        }
        var clock = Clock.systemUTC();
        MessageRepositoryPort messageRepoPort = new JdbcMessageRepositoryAdapter(new MessageRepository(ds, clock));
        var chatPersistencePort = new JdbcChatPersistenceAdapter(ds, ds, clock, UUID::randomUUID, 5);
        service = new ReadReceiptService(
            new JdbcMessageReadReceiptAdapter(ds),
            chatPersistencePort,
            messageRepoPort,
            new JdbcChatReadStateAdapter(ds),
            new JdbcUserLookupAdapter(ds),
            new AuditPort() {
                @Override
                @SuppressWarnings("java:S6213") // AuditPort contract uses reserved name "record"
                public void record(UUID actorUserId, String action, String resourceType, String resourceId, String detailsJson) { // NOSONAR S6213 — AuditPort.record
                    // no-op stub: H2 tests do not assert audit writes for read receipts
                }

                @Override
                public java.util.List<AuditRow> listRecent(int limit) {
                    return java.util.List.of();
                }

                @Override
                public java.util.List<AuditRow> listRecent(int limit, String actionEquals) {
                    return java.util.List.of();
                }

                @Override
                public java.util.List<AuditRow> listRecent(int limit, String actionEquals, String resourceTypeEquals) {
                    return java.util.List.of();
                }

                @Override
                public java.util.List<AuditRow> listRecent(int limit, String actionEquals, String resourceTypeEquals, String resourceIdEquals) {
                    return java.util.List.of();
                }

                @Override
                public long countByAction(String action) {
                    return 0L;
                }

                @Override
                public java.util.Optional<Instant> latestOccurredAtByAction(String action) {
                    return java.util.Optional.empty();
                }
            },
            new RecordingNats(),
            new AppConfig(),
            clock,
            NoOpReadCacheAdapter.INSTANCE
        );
    }

    private void insertUser(UUID id) throws Exception {
        try (var c = ds.getConnection();
             var ps = c.prepareStatement("INSERT INTO users (id, display_name) VALUES (?, 'u')")) {
            ps.setObject(1, id);
            ps.executeUpdate();
        }
    }

    @AfterEach
    void tearDown() {
        if (ds != null) {
            ds.close();
        }
    }

    @Test
    void markMessageRead_ok() {
        assertEquals(
            ReadReceiptService.MarkResult.OK,
            service.markMessageRead(chatId, readerId, messageId)
        );
    }

    @Test
    void markBatchRead_ok() {
        assertEquals(
            ReadReceiptService.MarkResult.OK,
            service.markBatchRead(chatId, readerId, java.util.List.of(messageId))
        );
    }

    static final class RecordingNats implements NatsOutboundPort {
        @Override
        public void publish(String subject, byte[] payload) {
            // no-op: captures not needed; service only publishes side-effect events
        }

        @Override
        public void flush(Duration timeout) {
            // no-op stub for NatsOutboundPort in unit tests
        }

        @Override
        public void publishPipelineMessageSend(byte[] payload, String userId) {
            // no-op stub for NatsOutboundPort in unit tests
        }
    }
}
