events {
    worker_connections 128;
}

http {
    upstream connector {
        server connector-runtime:8091;
    }
    upstream echo_php {
        server echo-php:8080;
    }
    upstream echo_go {
        server echo-go:8080;
    }
    upstream bitrix_bot {
        server bitrix24-crm-bot:8080;
    }
    upstream echo_ps {
        server echo-powershell:8087;
    }

    server {
        listen 8090;

        location /connector/ {
            proxy_pass http://connector/;
        }
        location /echo-php/ {
            proxy_pass http://echo_php/;
        }
        location /echo-go/ {
            proxy_pass http://echo_go/;
        }
        location /bitrix/ {
            proxy_pass http://bitrix_bot/;
        }
        location /echo-ps/ {
            proxy_pass http://echo_ps/;
        }
        location /health {
            return 200 'ok';
            add_header Content-Type text/plain;
        }
    }
}
