package com.avandocmsg.messenger.worker.botdelivery;

import com.avandocmsg.messenger.common.dto.MessageWorkerEvent;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class BotDeliveryTargetsTest {

    private static final UUID CHAT_ID = UUID.fromString("00000000-0000-0000-0000-000000000010");
    private static final UUID BOT_A = UUID.fromString("00000000-0000-0000-0000-000000000020");
    private static final UUID BOT_B = UUID.fromString("00000000-0000-0000-0000-000000000021");

    private com.zaxxer.hikari.HikariDataSource dataSource;

    @BeforeEach
    void setUp() throws Exception {
        dataSource = BotDeliveryTargets.testDataSource();
        try (var conn = dataSource.getConnection(); var st = conn.createStatement()) {
            st.execute("""
                CREATE TABLE IF NOT EXISTS bots (
                    id UUID PRIMARY KEY,
                    owner_id UUID NOT NULL,
                    bot_name VARCHAR(64) NOT NULL,
                    access_token_hash VARCHAR(64) NOT NULL,
                    listen_mode VARCHAR(16) NOT NULL DEFAULT 'READ_ALL',
                    default_webhook_url TEXT
                )
                """);
            st.execute("""
                CREATE TABLE IF NOT EXISTS bot_webhook_subscriptions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    chat_id UUID NOT NULL,
                    webhook_url TEXT NOT NULL,
                    bot_id UUID
                )
                """);
            st.execute("DELETE FROM bot_webhook_subscriptions");
            st.execute("DELETE FROM bots");
        }
    }

    @AfterEach
    void tearDown() {
        if (dataSource != null) {
            dataSource.close();
        }
    }

    @Test
    void loadWebhookTargets_singleQueryReturnsAllBotsForChat() throws Exception {
        insertBot(BOT_A, "bot_a", "READ_ALL", "https://default-a.test/hook");
        insertBot(BOT_B, "bot_b", "READ_ALL", null);
        insertSubscription(BOT_A, "https://chat-a.test/hook");
        insertSubscription(BOT_B, "https://chat-b.test/hook");

        try (var conn = dataSource.getConnection()) {
            var rows = BotDeliveryTargets.loadWebhookTargets(conn, CHAT_ID);
            assertEquals(2, rows.size());
            assertEquals("https://chat-a.test/hook", rows.get(0).subscriptionWebhookUrl());
            assertEquals("https://chat-b.test/hook", rows.get(1).subscriptionWebhookUrl());
        }
    }

    @Test
    void loadWebhookTargets_appliesLimit() throws Exception {
        for (int i = 0; i < BotDeliveryTargets.MAX_SUBSCRIPTIONS_PER_CHAT + 5; i++) {
            insertSubscription(null, "https://legacy-" + i + ".test/hook");
        }

        try (var conn = dataSource.getConnection()) {
            var rows = BotDeliveryTargets.loadWebhookTargets(conn, CHAT_ID);
            assertEquals(BotDeliveryTargets.MAX_SUBSCRIPTIONS_PER_CHAT, rows.size());
        }
    }

    @Test
    void prefetch_singleConnectionForRepeatedChatLookups() throws Exception {
        insertBot(BOT_A, "bot_a", "READ_ALL", null);
        insertSubscription(BOT_A, "https://chat-a.test/hook");

        var counting = new CountingDataSource(dataSource);
        var prefetch = new BotDeliveryTargets.Prefetch(counting);

        assertEquals(1, prefetch.forChat(CHAT_ID).size());
        assertEquals(1, prefetch.forChat(CHAT_ID).size());
        assertEquals(1, prefetch.forChat(CHAT_ID).size());
        assertEquals(1, counting.connections.get());
    }

    @Test
    void resolveForEvent_filtersByListenMode() throws Exception {
        var rows = List.of(
            new BotDeliveryTargets.SubscriptionRow(BOT_A, null, "helpdesk", "MENTIONS_ONLY", "https://default.test/hook"),
            new BotDeliveryTargets.SubscriptionRow(BOT_B, "https://all.test/hook", "broadcast", "READ_ALL", null)
        );
        var mentioned = new MessageWorkerEvent(
            "m1", CHAT_ID.toString(), "u1", null, 1L, "text", 0, false, 5, "please @helpdesk help", null);
        var targets = BotDeliveryTargets.resolveForEvent(mentioned, rows);

        assertEquals(2, targets.size());
        assertTrue(targets.stream().anyMatch(t -> t.webhookUrl().equals("https://default.test/hook")));
        assertTrue(targets.stream().anyMatch(t -> t.webhookUrl().equals("https://all.test/hook")));
    }

    @Test
    void resolveForEvent_skipsMentionsOnlyWithoutAtBot() throws Exception {
        var rows = List.of(
            new BotDeliveryTargets.SubscriptionRow(BOT_A, "https://chat.test/hook", "helpdesk", "MENTIONS_ONLY", null)
        );
        var plain = new MessageWorkerEvent(
            "m1", CHAT_ID.toString(), "u1", null, 1L, "text", 0, false, 5, "hello world", null);
        assertTrue(BotDeliveryTargets.resolveForEvent(plain, rows).isEmpty());
    }

    private void insertBot(UUID botId, String name, String listenMode, String defaultUrl) throws SQLException {
        try (var conn = dataSource.getConnection(); var st = conn.prepareStatement("""
            INSERT INTO bots (id, owner_id, bot_name, access_token_hash, listen_mode, default_webhook_url)
            VALUES (?, ?, ?, 'hash', ?, ?)
            """)) {
            st.setObject(1, botId);
            st.setObject(2, UUID.randomUUID());
            st.setString(3, name);
            st.setString(4, listenMode);
            st.setString(5, defaultUrl);
            st.executeUpdate();
        }
    }

    private void insertSubscription(UUID botId, String webhookUrl) throws SQLException {
        try (var conn = dataSource.getConnection(); var st = conn.prepareStatement("""
            INSERT INTO bot_webhook_subscriptions (chat_id, webhook_url, bot_id) VALUES (?, ?, ?)
            """)) {
            st.setObject(1, CHAT_ID);
            st.setString(2, webhookUrl);
            st.setObject(3, botId);
            st.executeUpdate();
        }
    }

    private static final class CountingDataSource implements DataSource {
        private final DataSource delegate;
        final AtomicInteger connections = new AtomicInteger();

        CountingDataSource(DataSource delegate) {
            this.delegate = delegate;
        }

        @Override
        public Connection getConnection() throws SQLException {
            connections.incrementAndGet();
            return delegate.getConnection();
        }

        @Override
        public Connection getConnection(String username, String password) throws SQLException {
            return getConnection();
        }

        @Override
        public java.io.PrintWriter getLogWriter() {
            return null;
        }

        @Override
        public void setLogWriter(java.io.PrintWriter out) {
        }

        @Override
        public void setLoginTimeout(int seconds) {
        }

        @Override
        public int getLoginTimeout() {
            return 0;
        }

        @Override
        public java.util.logging.Logger getParentLogger() {
            return java.util.logging.Logger.getGlobal();
        }

        @Override
        public <T> T unwrap(Class<T> iface) throws SQLException {
            if (iface.isInstance(delegate)) {
                return iface.cast(delegate);
            }
            return delegate.unwrap(iface);
        }

        @Override
        public boolean isWrapperFor(Class<?> iface) {
            return iface.isInstance(delegate);
        }
    }
}
