FROM gradle:jdk25 AS builder
WORKDIR /app
COPY . .
RUN gradle :modules:workers:archiver:installDist --no-daemon -x test

FROM eclipse-temurin:25-jre
WORKDIR /app
COPY --from=builder /app/modules/workers/archiver/build/install/archiver /app/archiver
ENTRYPOINT ["/app/archiver/bin/archiver"]
