FROM gradle:jdk25-noble AS builder
WORKDIR /app
COPY . .
RUN gradle --console=plain :modules:workers:message-pipeline:installDist --no-daemon -x test

FROM eclipse-temurin:25-jdk
WORKDIR /app
COPY --from=builder /app/modules/workers/message-pipeline/build/install/message-pipeline /app/message-pipeline
ENTRYPOINT ["/app/message-pipeline/bin/message-pipeline"]
