FROM gradle:jdk25-noble AS builder
WORKDIR /app
COPY . .
RUN gradle --console=plain :modules:workers:retention:installDist --no-daemon -x test

FROM eclipse-temurin:25-jdk
RUN apt-get update \
  && apt-get install -y --no-install-recommends curl \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/modules/workers/retention/build/install/retention /app/retention
ENV JAVA_TOOL_OPTIONS="-XX:MaxRAMPercentage=50.0 -XX:+UseContainerSupport -XX:+UseG1GC"
ENTRYPOINT ["/app/retention/bin/retention"]
