FROM gradle:jdk25 AS builder
WORKDIR /app
COPY . .
RUN gradle :modules:workers:deep-archiver:installDist --no-daemon -x test

FROM eclipse-temurin:25-jre
WORKDIR /app
COPY --from=builder /app/modules/workers/deep-archiver/build/install/deep-archiver /app/deep-archiver
ENTRYPOINT ["/app/deep-archiver/bin/deep-archiver"]
