package com.avandocmsg.messenger.api.admin.ui;

import com.avandocmsg.messenger.api.config.AppConfig;
import com.avandocmsg.messenger.core.port.NatsConnectionStatus;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Statement;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AdminServerStatsServiceTest {

    private HikariDataSource ds;
    private AdminServerStatsService service;

    @BeforeEach
    void init() throws Exception {
        var cfg = new HikariConfig();
        cfg.setJdbcUrl("jdbc:h2:mem:admin_stats_" + UUID.randomUUID().toString().replace("-", "") + ";DB_CLOSE_DELAY=-1");
        cfg.setMaximumPoolSize(2);
        ds = new HikariDataSource(cfg);
        try (var c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE users (id UUID PRIMARY KEY)");
            st.execute("CREATE TABLE chats (id UUID PRIMARY KEY)");
            st.execute("CREATE TABLE messages (id UUID PRIMARY KEY)");
            st.execute("""
                CREATE TABLE export_jobs (
                  id UUID PRIMARY KEY,
                  chat_id UUID NOT NULL,
                  requested_by UUID NOT NULL,
                  status VARCHAR(32) NOT NULL,
                  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                )
                """);
            st.execute("""
                CREATE TABLE audit_events (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
                  action VARCHAR(64) NOT NULL,
                  resource_type VARCHAR(64),
                  resource_id VARCHAR(128)
                )
                """);
            st.execute("INSERT INTO export_jobs (id, chat_id, requested_by, status) VALUES ('"
                + UUID.randomUUID() + "', '" + UUID.randomUUID() + "', '" + UUID.randomUUID() + "', 'queued')");
            st.execute("INSERT INTO export_jobs (id, chat_id, requested_by, status) VALUES ('"
                + UUID.randomUUID() + "', '" + UUID.randomUUID() + "', '" + UUID.randomUUID() + "', 'processing')");
            st.execute("INSERT INTO export_jobs (id, chat_id, requested_by, status) VALUES ('"
                + UUID.randomUUID() + "', '" + UUID.randomUUID() + "', '" + UUID.randomUUID() + "', 'export_v1')");
            st.execute("INSERT INTO export_jobs (id, chat_id, requested_by, status) VALUES ('"
                + UUID.randomUUID() + "', '" + UUID.randomUUID() + "', '" + UUID.randomUUID() + "', 'export_failed')");
            st.execute("INSERT INTO export_jobs (id, chat_id, requested_by, status) VALUES ('"
                + UUID.randomUUID() + "', '" + UUID.randomUUID() + "', '" + UUID.randomUUID() + "', 'export_cancelled')");
            st.execute("INSERT INTO audit_events (occurred_at, action) VALUES (CURRENT_TIMESTAMP, 'export.requested')");
            st.execute("INSERT INTO audit_events (occurred_at, action) VALUES (CURRENT_TIMESTAMP, 'export.suggested')");
            st.execute("INSERT INTO audit_events (occurred_at, action) VALUES (CURRENT_TIMESTAMP, 'export.admin_cancelled')");
        }
        AppConfig appConfig = new AppConfig() {
            @Override
            public String version() {
                return "test";
            }

            @Override
            public String redisUri() {
                return "redis://127.0.0.1:1";
            }
        };
        NatsConnectionStatus nats = () -> false;
        service = new AdminServerStatsService(ds, appConfig, nats);
    }

    @AfterEach
    void tearDown() {
        if (ds != null) {
            ds.close();
        }
    }

    @Test
    void snapshot_includesExportComplianceCounts() {
        var snap = service.snapshot();
        var ec = snap.exportCompliance();
        assertTrue(ec.available());
        assertEquals(5, ec.jobsTotal());
        assertEquals(1, ec.jobsQueued());
        assertEquals(1, ec.jobsProcessing());
        assertEquals(0, ec.jobsProcessingStale());
        assertEquals(30, ec.processingStaleMinutes());
        assertEquals(1, ec.jobsCompleted());
        assertEquals(1, ec.jobsFailed());
        assertEquals(1, ec.jobsCancelled());
        assertEquals(3, ec.auditExportEvents7d());
        assertEquals(1, ec.auditExportCancelled7d());
    }
}
