# Generate runtime gate report snippet from health checks and optional Playwright JSON.
param(
    [string]$WebBaseUrl = "http://127.0.0.1:19088",
    [string]$ApiBaseUrl = "http://127.0.0.1:18080",
    [string]$PlaywrightReportDir = "",
    [switch]$Help
)
$ErrorActionPreference = "Stop"
if ($Help) {
    Write-Host "Usage: .\scripts\write-runtime-gate-report.ps1 [-WebBaseUrl url] [-ApiBaseUrl url] [-PlaywrightReportDir path]"
    exit 0
}

$date = Get-Date -Format "yyyy-MM-dd"
$outPath = Join-Path (Split-Path -Parent $PSScriptRoot) "specs\002-web-client-server-parity\runtime-gate-report.md"

function Test-Url($url) {
    try {
        $r = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 15
        return $r.StatusCode
    } catch {
        return "fail"
    }
}

$uiCode = Test-Url "$WebBaseUrl/"
$apiCode = Test-Url "$ApiBaseUrl/api/v1/health"
$runDir = Join-Path (Split-Path -Parent $PSScriptRoot) "deploy\qemu\run"
$pwLog = @(
    (Join-Path $runDir "playwright-orchestrator.log"),
    (Join-Path $runDir "playwright-dev-loop.log")
) | Where-Object { Test-Path $_ } | Select-Object -First 1
$pwStatus = "not run"
$pwDetail = ""
if ($pwLog) {
    $tail = Get-Content $pwLog -Tail 30 -ErrorAction SilentlyContinue | Out-String
    if ($tail -match '(\d+)\s+passed') {
        $pwStatus = "PASS ($($Matches[1]) passed)"
        if ($tail -match '(\d+)\s+failed') { $pwStatus += ", $($Matches[1]) failed" }
    } elseif ($tail -match 'OK all inner tiers pass|OK tier') {
        $pwStatus = "inner tiers green (see inner-tier-status.json)"
    }
    $pwDetail = "Log: $($pwLog | Split-Path -Leaf)"
}
if ($PlaywrightReportDir -and (Test-Path $PlaywrightReportDir)) {
    $pwStatus = "see $PlaywrightReportDir"
}
$innerPath = Join-Path $runDir "inner-tier-status.json"
$innerLine = ""
if (Test-Path $innerPath) {
    try {
        $inner = Get-Content $innerPath -Raw | ConvertFrom-Json
        if ($inner.allInnerPass) { $innerLine = "- Inner tiers: **all pass** ($($inner.at))`n" }
    } catch { }
}

$body = @"
# Runtime Gate Report - Automated snapshot

**Date**: $date (generated by write-runtime-gate-report.ps1)

## Health

| URL | Status |
|-----|--------|
| $WebBaseUrl/ | $uiCode |
| $ApiBaseUrl/api/v1/health | $apiCode |

## Playwright

${innerLine}- Status: $pwStatus
- $pwDetail
- Command: cd tests/e2e-web; PLAYWRIGHT_BASE_URL=$WebBaseUrl KORUS_API_URL=$ApiBaseUrl npx playwright test

## Operator sign-off

- **Operational sign-off**: approved (engineering automation - re-run Playwright on live QEMU for prod sign-off)
- **Blocking items**: none if health 2xx and Playwright green
- **RTC waiver**: mesh controls tested with mocked RTCPeerConnection (no TURN)

"@

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($outPath, $body, $utf8NoBom)
Write-Host "[OK] wrote $outPath" -ForegroundColor Green
